CremitHQ/nebula

- Cargo.lock
- crates/tessera-storage/src/shield/aes.rs
This pull request is a follow-up to PR #20 and implements an AES GCM-based shield storage system, akin to the functionality of seal/unseal in Hashicorp Vault. The new feature significantly enhances data security by utilizing advanced encryption methods, ensuring that the stored data is protected from unauthorized access. 
Additionally, the `master_key` will leverage Shamir Secret Sharing schema and will also integrate a proactive secret sharing algorithm, further safeguarding sensitive information. (https://github.com/CremitHQ/tessera/issues/22)
Detailed implementation information and any necessary configurations are included to facilitate a smooth integration of this feature.
> feat(shield): implement AES GCM-based shield storage system

- crates/tessera-abe/src/curves/mod.rs
- crates/tessera-abe/src/schemes/rw15.rs
- crates/tessera-abe/src/utils/secret_shares.rs
This pull request implements  changes to ensure proper ownership and safety by removing the `Copy` trait and replacing it with explicit calls to `clone()`. This change enhances clarity and avoids unintended ownership issues.
> fix(abe): removing the `Copy` trait and replacing it with explicit calls to `clone()`

- Cargo.lock
- crates/tessera-backbone/Cargo.toml
- crates/tessera-backbone/src/application/mod.rs
- crates/tessera-backbone/src/application/secret/mod.rs
- crates/tessera-backbone/src/database/applied_policy.rs
- crates/tessera-backbone/src/database/mod.rs
- crates/tessera-backbone/src/database/secret_metadata.rs
- crates/tessera-backbone/src/domain/mod.rs
- crates/tessera-backbone/src/domain/secret/mod.rs
- crates/tessera-backbone/src/server/mod.rs
- crates/tessera-backbone/src/server/router/mod.rs
- crates/tessera-backbone/src/server/router/secret/mod.rs
- crates/tessera-backbone/src/server/router/secret/response/mod.rs
- Implement a feature to retrieve a list of secrets excluding the ones accessed from secret storage.
This pull request implements the secret retrieval feature for the backbone server. In this pull request, only the implementation using the PostgreSQL repository is included. The feature for retrieving the encrypted secrets will need to be added after the storage implementation is completed.
> impl get secrets from backbone server

- crates/tessera-storage/src/backend/file.rs
- crates/tessera-storage/src/shield/aes.rs
- crates/tessera-storage/src/shield/mod.rs
This pull request refactors the lifetime annotations in the `AESShieldStorage` module to enhance memory safety and clarify ownership semantics. The updates aim to improve code readability and maintainability without altering the existing functionality.
> refactor: update lifetime annotations in AESShieldStorage

- crates/tessera-storage/src/backend/file.rs
- crates/tessera-storage/src/lib.rs
- crates/tessera-storage/src/shield/aes.rs
This pull request updates the storage get methods to return an Option type instead of a standard type. This change will improve the handling of non-existent values, allowing for more robust and safer code by utilizing Rust's option types.
> feat(storage): update storage get methods to return Option type

- crates/tessera-abe/src/curves/bls24479.rs
- crates/tessera-abe/src/curves/bls48556.rs
- crates/tessera-abe/src/curves/mod.rs
- crates/tessera-abe/src/utils/secret_shares.rs
This pull request introduces an implementation of the `From<u64>` trait for various field types. This enhancement allows for more seamless conversion from unsigned 64-bit integers
> feat: add From<u64> implementation for field types

- crates/tessera-abe-wasm/src/lib.rs
- crates/tessera-abe/src/curves/bls24479.rs
- crates/tessera-abe/src/curves/bls48556.rs
- crates/tessera-abe/src/curves/mod.rs
- crates/tessera-abe/src/schemes/rw15.rs
This pull request introduces the `Clone` derive attribute to several structs within the `abe` module.
> fix(abe): add Clone derive to several structs for better usability

- crates/tessera-secret-sharing/src/gf256.rs
- crates/tessera-secret-sharing/src/shamir.rs
This pull request introduces serialization and zeroing mechanisms for the GF256 and Share structs. These enhancements are aimed at improving data management and integrity within the system, ensuring that both data is serialized for storage and that it can be securely zeroed when no longer needed.
> feat: add serialization and zeroing for GF256 and Share structs

- Cargo.lock
- crates/tessera-backbone/Cargo.toml
- crates/tessera-backbone/src/application/secret/mod.rs
- crates/tessera-backbone/src/database/mod.rs
- crates/tessera-backbone/src/database/secret_value.rs
- crates/tessera-backbone/src/domain/secret/mod.rs
- crates/tessera-backbone/src/server/router/secret/mod.rs
- crates/tessera-backbone/src/server/router/secret/request.rs
- crates/tessera-backbone/src/server/router/secret/response/mod.rs
This PR implements a feature that persists cipher text in the database. The implementation assumes a PostgreSQL repository, so additional work is required to support other repositories.
> feat(backbone): impl persisting secret cipher to database

- crates/tessera-backbone/src/application/secret/mod.rs
- crates/tessera-backbone/src/domain/secret/mod.rs
- crates/tessera-backbone/src/server/router/secret/mod.rs
- crates/tessera-backbone/src/server/router/secret/response/mod.rs
This PR implements a feature that functionality to include the cipher text when responding secret data. The implementation assumes a PostgreSQL repository, so additional work is required to support other repositories.
> feat(backbone): Response secret with cipher

- crates/tessera-backbone/src/database/parameter.rs
- crates/tessera-backbone/src/domain/parameter/mod.rs
This pull request refactors the serialization method used for the global parameter in the Backbone module. The previous serialization approach using `serde_json` has been replaced with `rmp_serde`
> refactor(backbone): switch serialization from serde_json to rmp_serde for global parameter

- crates/tessera-authority/src/domain/authority.rs
- crates/tessera-authority/src/domain/backbone.rs
- crates/tessera-authority/src/domain/key_pair.rs
- crates/tessera-authority/src/server/mod.rs
- crates/tessera-authority/src/server/router/init/mod.rs
- crates/tessera-authority/src/server/router/mod.rs
- crates/tessera-authority/src/server/router/pubkey/mod.rs
This PR introduces an endpoint for retrieving the public key, enhancing the authority module's capabilities. It also includes improvements to error handling for authority initialization, ensuring more robust and clear interactions. Additionally, recent changes have refined the method for retrieving key pairs by version, and adjusted parameter types for enhanced decoding in the BackboneClient.
In commit [48cc518](https://github.com/CremitHQ/tessera/pull/68/commits/48cc5183f5b120d696ac6d1eb73416484c0dcbc5), I implemented the initialization of KeyPair storage followed immediately by the disarm process. This approach deviates from conventional methods, such as HashiCorp Vault’s initialization process, which requires unsealing before accessing the physical backend. While this design enhances …
> feat(authority): Add getting the public key endpoint

- crates/tessera-abe/src/error.rs
- crates/tessera-abe/src/schemes/rw15.rs
- crates/tessera-abe/src/utils/aes.rs
- crates/tessera-abe/src/utils/secret_shares.rs
- crates/tessera-policy/src/error.rs
- crates/tessera-policy/src/pest/human.rs
- crates/tessera-policy/src/pest/json.rs
- crates/tessera-policy/src/pest/mod.rs
- crates/tessera-storage/src/backend/file.rs
- crates/tessera-storage/src/shield/aes.rs
- crates/tessera-storage/src/shield/mod.rs
This pull request refactors the error handling in the policy system to improve clarity and type safety. Key changes include:
- Streamlining error handling and type definitions in the storage module.
- Renaming `PolicyError` to `PolicyParserError` to better reflect its purpose, along with modifications to the error details.
- Replacing error details with more consistent error types in the ABE module.
- Implementing key validation to prevent the usage of ".." in storage paths.
This refactor aims to enhance maintainability and reduce potential bugs related to error handling.
https://rust-lang.github.io/api-guidelines/interoperability.html?highlight=message#error-types-are-meaningful-and-well-behaved-c-good-err
https://rust-lang.github.io/api-guidelines/naming.html#names-use-a-consistent-word- …
> refactor: improve clarity for error handling and validation

- crates/tessera-abe/src/error.rs
- crates/tessera-abe/src/schemes/rw15.rs
- crates/tessera-abe/src/utils/secret_shares.rs
- crates/tessera-abe/src/utils/tools.rs
- crates/tessera-policy/src/error.rs
- crates/tessera-policy/src/pest/human.rs
- crates/tessera-policy/src/pest/json.rs
- crates/tessera-policy/src/pest/mod.rs
This pull request refactors the policy tree nodes to be constructed using a b-tree structure. This change aims to enable the construction of a Monotone Span Program (MSP)
> refactor(policy): policy tree nodes to construct with a b-tree

- Cargo.lock
- crates/tessera-abe/src/schemes/rw15.rs
- crates/tessera-abe/src/utils/mod.rs
- crates/tessera-abe/src/utils/secret_shares.rs
- crates/tessera-policy/Cargo.toml
- crates/tessera-policy/src/lib.rs
- crates/tessera-policy/src/msp.rs
- crates/tessera-policy/src/pest/human.rs
- crates/tessera-policy/src/pest/json.rs
- crates/tessera-policy/src/pest/mod.rs
- crates/tessera-policy/src/utils.rs
This pull request introduces the MonotoneSpanProgram (MSP) functionality for policies. These changes were made to implement schemes that utilize Monotone Span Programs (MSP).
> feat: add MonotoneSpanProgram(MSP) for policy 

- crates/tessera-abe/src/curves/bn462.rs
- crates/tessera-abe/src/curves/mod.rs
- crates/tessera-abe/src/schemes/isabella24.rs
- crates/tessera-miracl/src/bn462/big.rs
- crates/tessera-miracl/src/bn462/ecp.rs
- crates/tessera-miracl/src/bn462/ecp2.rs
- crates/tessera-miracl/src/bn462/fp.rs
- crates/tessera-miracl/src/bn462/fp12.rs
- crates/tessera-miracl/src/bn462/fp2.rs
- crates/tessera-miracl/src/bn462/fp4.rs
This pull request introduces the integration of the Bn462 pairing-friendly curve, enhancing the capabilities of the ABE module. This feature aims to improve cryptographic operations by utilizing a lightweight pairing-friendly curve, thereby optimizing performance and resource efficiency. 
https://www.ietf.org/archive/id/draft-irtf-cfrg-pairing-friendly-curves-11.html#section-4.2.2
> feat(abe): integrate Bn462 pairing-friendly curve

- crates/nebula-backbone/src/application/path/mod.rs
- crates/nebula-backbone/src/database/applied_path_policy.rs
- crates/nebula-backbone/src/database/applied_path_policy_allowed_action.rs
- crates/nebula-backbone/src/database/mod.rs
- crates/nebula-backbone/src/database/path.rs
- crates/nebula-backbone/src/domain/secret/mod.rs
- crates/nebula-backbone/src/server/router/path/mod.rs
- crates/nebula-backbone/src/server/router/path/model.rs
- crates/nebula-backbone/src/server/router/path/request.rs
- crates/nebula-backbone/src/server/router/path/response.rs
This PR extends the path-related API to enable the management of policies for paths. As before, PostgreSQL is used for storage.
> manage path policy

- crates/nebula-authorization/src/database/machine_identity_token.rs
- crates/nebula-authorization/src/database/mod.rs
- crates/nebula-authorization/src/domain/machine_identity/mod.rs
- crates/nebula-authorization/src/server/router/mod.rs
This PR implements a set of APIs for managing machine identity tokens. The implemented APIs are as follows:
GET machine identity tokens
GET single machine identity token
POST machine identity token
DELETE machine identity token
> impl APIs for managing machine identity tokens

- crates/nebula-authorization/src/application.rs
- crates/nebula-authorization/src/domain/connector/mod.rs
- crates/nebula-authorization/src/domain/machine_identity/mod.rs
- crates/nebula-authorization/src/domain/mod.rs
- crates/nebula-authorization/src/domain/token/mod.rs
- crates/nebula-authorization/src/server/router/mod.rs
This pull request introduces the functionality to issue JSON Web Tokens (JWT) for machine identities. This feature is essential for enhancing the security and authentication processes for our application's automated systems by providing them with secure tokens for identity verification without human intervention. 
Note: Please remember to implement access control for sub-paths related to machine identity using tokens in the future.
> feat: implement issuing the JWT for a machine identity

- crates/nebula-authorization/src/domain/machine_identity/mod.rs
- crates/nebula-authorization/src/server/router/mod.rs
This PR excludes attribute registration during the process of creating machine identities. At this stage, the registration of machine identities should be open to all members; however, the responsibility for managing attributes lies with the administrator. Therefore, attributes should not be registered simultaneously when creating machine identities. Once the authorization server is capable of persistently managing member attributes, this feature should be re-enabled.
> remove attributes from registering machine identity logic

- Cargo.lock
- crates/nebula-authority/Cargo.toml
- crates/nebula-authority/src/config.rs
- crates/nebula-authority/src/database.rs
- crates/nebula-authority/src/domain/authority.rs
- crates/nebula-authority/src/domain/key_pair.rs
- crates/nebula-authority/src/main.rs
- crates/nebula-authorization/src/database/mod.rs
- crates/nebula-backbone/src/database/mod.rs
- crates/nebula-storage/src/backend/postgres.rs
This pull request introduces a new service called `PostgresKeyPairService`, which is designed to handle the management of key pairs within a PostgreSQL database environment. The service encapsulates the logic required to create, retrieve, and manage ABE authority key-pairs.
> feat: add PostgresKeyPairService for key management

- crates/nebula-backbone/src/application/mod.rs
- crates/nebula-backbone/src/application/workspace/mod.rs
- crates/nebula-backbone/src/domain/workspace/workspace_service.rs
This PR fixes a bug where the workspace table schema migration always fails. The bug occurs because the table schema migration is executed before the transaction creating the database schema is completed. The bug is fixed by separating the transaction for creating the database schema.
> create shcema without transaction

- crates/nebula-authorization/src/database/workspace_migration/m20241128_001_init_authorization.rs
- crates/nebula-backbone/src/database/migration/m20241126_001_init_backbone.rs
- crates/nebula-backbone/src/database/workspace_migration/m20241126_001_init_backbone.rs
This pull request introduces a refactor in our database migration scripts by adding `IF NOT EXISTS` checks. These changes aim to enhance the reliability and idempotency of our migration processes, ensuring that scripts do not fail due to existing schema elements.
> refactor: add if_not_exists checks in migration scripts

- crates/nebula-authorization/src/server/router/mod.rs
This pull request fixes a bug where tuple-based path parameters were not being parsed correctly
> fix(authz): use structured params for workspace name

- crates/nebula-abe-wasm/src/lib.rs
> refactor: remove test-only mock functions from wasm

- crates/nebula-authority/src/server/mod.rs
- crates/nebula-backbone/src/server/mod.rs
This pull request improves the workspace path extraction process by transitioning from using tuples to custom-defined structures. Since tuples require a fixed number of elements, they were unsuitable for flexible path parsing. To address this limitation, I defined a new structure that allows for more adaptable handling of workspace paths
https://github.com/CremitHQ/nebula/pull/131
> feat: refactor workspace path extraction using structs

- crates/nebula-backbone/src/domain/authority/mod.rs
This pull request addresses an issue with the `delete` method within the backbone component by ensuring that instead of truly deleting, it correctly marks the authority as deleted.
> fix(backbone): correct delete authority method to mark as deleted

- crates/nebula-backbone/src/database/authority.rs
This pull request addresses a typo issue in our codebase related to the naming of a database table. Specifically, the table was incorrectly named and has now been renamed to "authority"
> fix(backbone): rename table to "authority"

- Cargo.lock
- Cargo.toml
- crates/nebula-authority/Cargo.toml
- crates/nebula-cli/Cargo.toml
- crates/nebula-cli/src/api/authority.rs
- crates/nebula-cli/src/api/authorization.rs
- crates/nebula-cli/src/api/backbone.rs
- crates/nebula-cli/src/api/mod.rs
- crates/nebula-cli/src/command/access_condition.rs
- crates/nebula-cli/src/command/login.rs
- crates/nebula-cli/src/command/mod.rs
- crates/nebula-cli/src/command/secret.rs
- crates/nebula-cli/src/main.rs
This pull request introduces two new command functionalities: Access Condition and Secret. With the addition of these commands, users gain the ability to manage access conditions and secrets directly through the command-line interface. 
- New commands have been added to allow users to list access conditions.
- This functionality helps in retrieving an overview of the access conditions that are currently configured.
```bash 
$ nebula access-condition list
```
- Users can now list, view individually (with decryption), and create (with encryption) secrets via the CLI.
- This provides a convenient way to handle sensitive data securely, ensuring that all operations maintain data privacy through encryption and decryption as needed.
```bash
$ nebula …
```
> feat(cli): Add access condition and secret command

- crates/nebula-authorization/src/server/router/mod.rs
- crates/nebula-token/src/jwt.rs
This pull request introduces an enhancement to the SAML authentication process by adding support for relaying ports via the RelayState parameter in the SAML callback. This allows for redirection back to a specific localhost port for the CLI login action.
> feat(authz): enhance SAML callback with port relay support

- crates/nebula-authority/src/main.rs
- crates/nebula-backbone/src/application/mod.rs
Summary of the changes: Migration from StaticJwksDiscovery to a cached approach for improved performance and resource utilization.
This pull request refactors the existing implementation by removing the `StaticJwksDiscovery` mechanism and replacing it with a more efficient cached approach. (default to 10min)
> refactor: remove StaticJwksDiscovery for cached approach

- config/authorization_config.toml.example
- crates/nebula-authorization/src/application.rs
- crates/nebula-authorization/src/config.rs
- crates/nebula-authorization/src/domain/connector/saml.rs
- crates/nebula-authorization/src/main.rs
This pull request introduces a new feature to support dynamic configuration of SAML admin roles within the system. With the new dynamic SAML admin role configuration, administrators can specify SAML attributes that define admin roles, removing the need for static role assignments. This feature leverages the existing SAML integration and extends it by parsing additional attributes provided in the SAML assertions.
> feat: support dynamic SAML admin role configuration

- crates/nebula-backbone/src/domain/secret/mod.rs
This pull request addresses a bug in our path management logic where the creation of new paths would fail due to the incorrect assumption that the root path is always present by default. The existing implementation includes a redundant check for the root path ("/"), which prevents new paths from being created when the root is absent. 
This update removes the unnecessary check, allowing new paths to be generated correctly and ensuring that the system properly handles the creation of the root path when necessary.
> fix: remove redundant path check for root "/"

- crates/nebula-backbone/src/database/workspace_migration/m20241206_001_remove_unused_column_applied_policy_table.rs
- crates/nebula-backbone/src/database/workspace_migration/mod.rs
This pull request addresses an issue with the `applied_policy` table by removing an unused column that was causing conflicts during data insertion. The `type` column was identified as redundant and has been removed to prevent insertion errors and improve table integrity.
#156
> fix: remove unused column from applied_policy table

- Cargo.lock
- Cargo.toml
- crates/nebula-backbone/src/application/mod.rs
- crates/nebula-backbone/src/application/workspace/mod.rs
- crates/nebula-backbone/src/domain/secret/mod.rs
- crates/nebula-backbone/src/server/mod.rs
- crates/nebula-backbone/src/server/router/workspace/mod.rs
this PR implements initializing process of root path and parameter when intializing workspaces.
and also merge workspaces router instead of nesting
> Initialize root path and parameter when initializing workspace
