- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/design_proposal.md
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/pull_request_template.md
This pull request introduces issue and pull request templates to enhance the contribution process for our project.
> chore: add issue and PR templates for better contributions

- .github/workflows/ci-tessera.yaml
This pull request introduces a new Continuous Integration (CI) workflow for the Tessera project tests.
> feat(ci): add CI workflow for Tessera project tests

- crates/tessera-storage/Cargo.toml
- crates/tessera-storage/src/lib.rs
- crates/tessera-storage/src/shield/mod.rs
**Description:**
This pull request introduces the initial implementation of storage and shield traits for the Tessera storage module. The primary goal of these changes is to establish a foundational structure that will support future enhancements and functionality.
**Changes Included:**
- Added initial storage traits to manage data persistence.
- Introduced shield traits to enhance data protection mechanisms.
> feat(tessera-storage): add initial storage and shield traits with deps

- CONTRIBUTING.md
- README.md
--- 
- Enhanced the overall structure of the README for better flow and readability.
- Added detailed contribution guidelines to facilitate the collaboration process among contributors.
> Update README.md details and Add the Contributing Guidelines.

- Cargo.lock
- Cargo.toml
This pull request updates the project's dependencies to the latest versions in accordance with the release of sea-orm v1.1.
> chore(deps): update dependencies to latest versions for sea-orm v1.1

- crates/tessera-abe/src/schemes/rw15.rs
- The individual elements (c1, c2, c3, c4) have been merged into a single structure (cx).
- This simplification aims to enhance code readability and maintainability.
- Efforts were made to ensure backward compatibility and minimal disruption in existing functionalities.
**Implications:**
This refactor may impact components that interact with the previous structure of the ciphertext.
> refactor: simplify ciphertext structure by consolidating c1-c4 into cx

- crates/tessera-backbone/src/server/mod.rs
- add router for health check
- add `GET /health` router
> add health check router

- crates/tessera-backbone/Dockerfile
- write tessera backbone dockerfile
- write tessera backbone dockerfile
> write tessera backbone dockerfile

- crates/tessera-abe/src/curves/bls48556.rs
- crates/tessera-abe/src/error.rs
- crates/tessera-abe/src/schemes/rw15.rs
- crates/tessera-abe/src/utils/aes.rs
- crates/tessera-abe/src/utils/secret_shares.rs
- crates/tessera-storage/src/backend/file.rs
This pull request introduces several important changes to improve error handling and fix a naming inconsistency in our codebase.
> refactor: update ABEError to use Cow for error messages

- Cargo.lock
- Cargo.toml
- crates/tessera-backbone/Cargo.toml
- crates/tessera-backbone/src/application/mod.rs
- crates/tessera-backbone/src/application/parameter/mod.rs
- crates/tessera-backbone/src/database/mod.rs
- crates/tessera-backbone/src/database/parameter.rs
- crates/tessera-backbone/src/domain/mod.rs
- crates/tessera-backbone/src/domain/parameter/mod.rs
- crates/tessera-backbone/src/server/mod.rs
- crates/tessera-backbone/src/server/router/mod.rs
- crates/tessera-backbone/src/server/router/parameter/mod.rs
- crates/tessera-backbone/src/server/router/parameter/response/mod.rs
This pull request introduces several enhancements to the backbone related to parameter management within our database. Key features include the addition of a new parameter model, changes in data type handling, and getting parameter model.
> feat(backbone): implement getting for parameter 

- crates/tessera-backbone/src/application/mod.rs
- crates/tessera-backbone/src/application/policy/mod.rs
- crates/tessera-backbone/src/database/mod.rs
- crates/tessera-backbone/src/database/policy.rs
- crates/tessera-backbone/src/domain/mod.rs
- crates/tessera-backbone/src/domain/policy/mod.rs
- crates/tessera-backbone/src/server/mod.rs
- crates/tessera-backbone/src/server/router/mod.rs
- crates/tessera-backbone/src/server/router/policy/mod.rs
- crates/tessera-backbone/src/server/router/policy/response.rs
this PR implements api and service implemnetations for getting policies from postgresql database. This implementation only includes read operations from PostgreSQL.
> impl getting managed policies

- crates/tessera-authority/src/domain/application.rs
- crates/tessera-authority/src/domain/key_pair.rs
- crates/tessera-authority/src/main.rs
Key pair service methods renamed for clarity; retrieval and generation logic added.
> feat(authority): Impl generating the key pair

- crates/tessera-backbone/src/application/mod.rs
- crates/tessera-backbone/src/application/path/mod.rs
- crates/tessera-backbone/src/database/mod.rs
- crates/tessera-backbone/src/database/path.rs
- crates/tessera-backbone/src/domain/secret/mod.rs
- crates/tessera-backbone/src/server/mod.rs
- crates/tessera-backbone/src/server/router/mod.rs
- crates/tessera-backbone/src/server/router/path/mod.rs
- crates/tessera-backbone/src/server/router/path/response.rs
this PR implements api and service implementations for getting paths from postgresql database. This implementation only includes read operations from PostgreSQL.
> feat(path): impl getting managed paths

- crates/tessera-abe/src/curves/mod.rs
- crates/tessera-abe/src/schemes/rw15.rs
- crates/tessera-abe/src/utils/secret_shares.rs
This pull request refactors the logic used for removing secret share indices, aiming to streamline the process and improve the overall efficiency and readability of the code.
> refactor: streamline secret share index removal logic and updates

- crates/tessera-backbone/src/application/mod.rs
- crates/tessera-backbone/src/application/path/mod.rs
- crates/tessera-backbone/src/application/secret/mod.rs
- crates/tessera-backbone/src/database/mod.rs
- crates/tessera-backbone/src/domain/policy/mod.rs
- crates/tessera-backbone/src/domain/secret/mod.rs
- crates/tessera-backbone/src/server/router/secret/mod.rs
- crates/tessera-backbone/src/server/router/secret/request.rs
- crates/tessera-backbone/src/server/router/secret/response/mod.rs
This pull request implements the functionality to store secrets. The implementation uses a PostgreSQL backend. The functionality to store encrypted text and secrets is not yet implemented and will require additional work after the PostgreSQL storage and the connection to the authority server are established.
> impl registering secret

- crates/tessera-backbone/src/server/response.rs
- crates/tessera-backbone/src/server/router/parameter/response/mod.rs
- crates/tessera-backbone/src/server/router/path/response.rs
- crates/tessera-backbone/src/server/router/policy/response.rs
- crates/tessera-backbone/src/server/router/secret/mod.rs
- crates/tessera-backbone/src/server/router/secret/request.rs
- crates/tessera-backbone/src/server/router/secret/response/mod.rs
- crates/tessera-backbone/src/server/router/workspace/request/mod.rs
- crates/tessera-backbone/src/server/router/workspace/response/mod.rs
Following the rules used in cremit, I changed the naming convention for API responses, requests, etc., to camelCase.
> fix(backbone): change snake_case into cameCase 

- crates/tessera-storage/src/backend/file.rs
This pull request addresses the issue of leading slashes being included in storage keys. The changes ensure that all storage keys are trimmed of leading slashes, providing a cleaner and more consistent key format.
Additionally, the reason for this modification is that the `.join()` methods interpret paths starting with a `/` as absolute paths and subsequently replace them based on the specified path. This behavior can pose security risks. For example, a request for `/etc/passwd` might lead to unauthorized access to sensitive files. 
Furthermore, it’s crucial for other storage layers to effectively handle exceptional cases, just as the file system does, to ensure robust security and reliability
> fix: trim leading slashes from storage keys

- Cargo.lock
- crates/tessera-backbone/Cargo.toml
- crates/tessera-backbone/src/application/parameter/mod.rs
- crates/tessera-backbone/src/server/router/parameter/mod.rs
- crates/tessera-backbone/src/server/router/parameter/response/mod.rs
This pull request updates the parameter response structure and serialization in the backbone component. The modifications aim to improve the handling of response data and ensure that it adheres to the protocol for data serialization/deserialization.
> feat(backbone): update parameter response structure and serialization

- crates/tessera-backbone/src/application/policy/mod.rs
- crates/tessera-backbone/src/server/router/policy/mod.rs
- crates/tessera-backbone/src/server/router/policy/response.rs
With this PR, we implement and expose an API that allows retrieving a single policy. The retrieval is implemented based on the PostgreSQL repository.
> impl getting single policy api

- crates/tessera-backbone/src/application/secret/mod.rs
- crates/tessera-backbone/src/database/applied_policy.rs
- crates/tessera-backbone/src/domain/secret/mod.rs
- crates/tessera-backbone/src/server/router/secret/mod.rs
- crates/tessera-backbone/src/server/router/secret/request.rs
- crates/tessera-backbone/src/server/router/secret/response/mod.rs
With this PR, we implement and expose an API that allows editing a secret. The editing is implemented based on the PostgreSQL repository.
> impl editing secret

- crates/tessera-backbone/src/application/path/mod.rs
- crates/tessera-backbone/src/application/secret/mod.rs
- crates/tessera-backbone/src/domain/secret/mod.rs
- crates/tessera-backbone/src/server/router/path/mod.rs
- crates/tessera-backbone/src/server/router/path/response.rs
- crates/tessera-backbone/src/server/router/path/reuqest.rs
With this PR, it implement and expose an API that allows registering a path. The registering is implemented based on the PostgreSQL repository.
Fixes #{bug number} (in this specific format)
> impl registering path

- crates/tessera-backbone/src/application/path/mod.rs
- crates/tessera-backbone/src/application/secret/mod.rs
- crates/tessera-backbone/src/domain/secret/mod.rs
- crates/tessera-backbone/src/server/router/path/mod.rs
- crates/tessera-backbone/src/server/router/path/response.rs
With this PR, it implement and expose an API that allows deleting a path. The deleting is implemented based on the PostgreSQL repository.
> impl deleting path

- crates/tessera-backbone/src/application/path/mod.rs
- crates/tessera-backbone/src/domain/secret/mod.rs
- crates/tessera-backbone/src/server/router/path/mod.rs
- crates/tessera-backbone/src/server/router/path/response.rs
- crates/tessera-backbone/src/server/router/path/reuqest.rs
With this PR, it implement and expose an API that allows editing a path. The editing is implemented based on the PostgreSQL repository.
> impl editing path

- Cargo.lock
- crates/tessera-backbone/Cargo.toml
- crates/tessera-backbone/src/application/policy/mod.rs
- crates/tessera-backbone/src/application/secret/mod.rs
- crates/tessera-backbone/src/domain/policy/mod.rs
- crates/tessera-backbone/src/server/router/policy/mod.rs
- crates/tessera-backbone/src/server/router/policy/request.rs
- crates/tessera-backbone/src/server/router/policy/response.rs
With this PR, it implement and expose an API that allows registering a policy. The registering is implemented based on the PostgreSQL repository.
> impl register policy

- crates/tessera-backbone/src/application/policy/mod.rs
- crates/tessera-backbone/src/application/secret/mod.rs
- crates/tessera-backbone/src/domain/policy/mod.rs
- crates/tessera-backbone/src/domain/secret/mod.rs
- crates/tessera-backbone/src/server/router/policy/mod.rs
- crates/tessera-backbone/src/server/router/policy/request.rs
With this PR, it implement and expose an API that allows editing a policy. The editing is implemented based on the PostgreSQL repository.
> impl editing policy

- crates/tessera-backbone/src/application/policy/mod.rs
- crates/tessera-backbone/src/domain/policy/mod.rs
- crates/tessera-backbone/src/server/router/policy/mod.rs
With this PR, it implement and expose an API that allows deleting a policy. The deleting is implemented based on the PostgreSQL repository.
> impl deleting policy

- docs/src/components/HomepageFeatures/index.tsx
- docs/src/components/HomepageFeatures/styles.module.css
- docs/src/css/custom.css
- docs/src/pages/index.module.css
- docs/src/pages/index.tsx
> docs: style Improvement

- Cargo.lock
- Cargo.toml
- crates/nebula-abe/Cargo.toml
- crates/nebula-idp/Cargo.toml
- crates/nebula-idp/src/domain/connector/mod.rs
- crates/nebula-idp/src/domain/connector/saml.rs
Enhance SAML support by adding the ability to handle custom claims efficiently.
This pull request introduces additional functionality to the SAML authentication flow, enabling the support for custom claims. This enhancement allows the application to retrieve and utilize custom claims provided by the SAML identity provider, thereby offering more flexibility and extensibility for user identity management. 
The key changes include:
- Parsing and mapping custom claims from SAML responses.
- Updating the user authentication logic to incorporate these custom claims.
- Adding corresponding unit tests to ensure the robustness of the new functionality.
- Amending documentation to guide developers on configuring and using custom claims within their SAML …
> feat(idp): enhance SAML support with custom claims

- crates/nebula-backbone/src/application/policy/mod.rs
- crates/nebula-backbone/src/application/secret/mod.rs
- crates/nebula-backbone/src/database/applied_policy.rs
- crates/nebula-backbone/src/domain/policy/mod.rs
- crates/nebula-backbone/src/domain/secret/mod.rs
- crates/nebula-backbone/src/server/router/secret/mod.rs
- crates/nebula-backbone/src/server/router/secret/request.rs
- crates/nebula-backbone/src/server/router/secret/response/mod.rs
- remove management policy of secret
- rename access policy to access condition
> remove management policy and rename access policy

- crates/nebula-authorization/Cargo.toml
- crates/nebula-authorization/src/application.rs
- crates/nebula-authorization/src/database/machine_identity.rs
- crates/nebula-authorization/src/database/machine_identity_attribute.rs
- crates/nebula-authorization/src/database/mod.rs
- crates/nebula-authorization/src/domain/machine_identity/mod.rs
- crates/nebula-authorization/src/domain/mod.rs
- crates/nebula-authorization/src/domain/oidc/utils/hash.rs
- crates/nebula-authorization/src/server/router/mod.rs
This PR implements a set of APIs for managing machine identities. The implemented APIs are as follows:
- GET machine identities
- GET single machine identity
- POST machine identity
- PATCH machine identity
- DELETE machine identity
Note that this PR does not address machine identity tokens. These will be implemented in a subsequent PR.
> manage machine identity

- crates/nebula-authority/src/server/mod.rs
- crates/nebula-authorization/src/application.rs
- crates/nebula-authorization/src/config.rs
- crates/nebula-authorization/src/domain/connector/mod.rs
- crates/nebula-authorization/src/domain/connector/saml.rs
- crates/nebula-authorization/src/server/router/mod.rs
- crates/nebula-token/src/claim.rs
This pull request introduces role-based access control (RBAC) enhancements with SAML updates to our authorization mechanism.
> feat: add role-based access control with SAML updates

- crates/nebula-authority/src/domain/authority.rs
- crates/nebula-authority/src/domain/backbone.rs
- crates/nebula-authority/src/domain/key_pair.rs
- crates/nebula-authority/src/server/mod.rs
- crates/nebula-authority/src/server/router/mod.rs
- crates/nebula-authority/src/server/router/userkey/mod.rs
- crates/nebula-backbone/src/application/parameter/mod.rs
- crates/nebula-backbone/src/domain/parameter/mod.rs
- crates/nebula-storage/src/shield/aes.rs
- crates/nebula-storage/src/shield/mod.rs
This pull request introduces the implementation of a new user key router, which includes an endpoint for managing user keys within a workspace. 
The changes include:
- A new function to check the shield initialization to ensure all components are properly initialized before executing key-related operations.
- Refactored naming and curve changes in the key pair service for better clarity and maintainability.
> feat(authority): Add user key router 

- crates/nebula-authority/src/config.rs
- crates/nebula-authority/src/main.rs
This pull request introduces the handling of disarm key shares in both the configuration and the main logic of the application. The changes involve updating the configuration to include settings specific to disarm key shares and ensuring that the main application logic appropriately processes these shares.
> feat(authority): add disarm key shares handling in config and main

- crates/nebula-authority/src/domain/authority.rs
- crates/nebula-authority/src/domain/key_pair.rs
- crates/nebula-authority/src/server/mod.rs
- crates/nebula-authority/src/server/router/init/mod.rs
- crates/nebula-authority/src/server/router/pubkey/mod.rs
- crates/nebula-authority/src/server/router/userkey/mod.rs
This PR introduces version handling mechanisms in the API endpoints that deal with public and user key responses.
> feat: add version handling to public and user key responses

- crates/nebula-authority/src/domain/authority.rs
- crates/nebula-authority/src/server/mod.rs
- crates/nebula-authority/src/server/router/keypair/mod.rs
- crates/nebula-authority/src/server/router/mod.rs
This pull request introduces a vital update to our system's security infrastructure by adding a new API endpoint to facilitate key pair rolling. The primary intention of this feature is to automate the management and rotation of cryptographic key pairs, thereby enhancing security by ensuring that keys are regularly updated, invalidated when necessary, and managed effectively
> feat: add key pair rolling API endpoint

- Cargo.lock
- Cargo.toml
- crates/nebula-authority/Cargo.toml
- crates/nebula-authority/src/domain/authority.rs
- crates/nebula-authority/src/domain/backbone.rs
- crates/nebula-authority/src/domain/key_pair.rs
- crates/nebula-authority/src/server/mod.rs
- crates/nebula-authority/src/server/router/disarm/mod.rs
- crates/nebula-authority/src/server/router/mod.rs
- crates/nebula-authorization/Cargo.toml
- crates/nebula-backbone/Cargo.toml
- crates/nebula-secret-sharing/Cargo.toml
- crates/nebula-secret-sharing/src/gf256.rs
- crates/nebula-secret-sharing/src/shamir.rs
This pull request introduces several enhancements:
1. **Removal of Unnecessary `Zeroizing` Logic**: 
- The previously implemented `Zeroizing` structure has been deemed unnecessary due to existing safeguards and is now removed. This simplifies our code and enhances performance without compromising security.
2. **Addition of `cached` Macro**:
- Introduces a `cached` macro which refactors existing logic to replace direct client calls with cached API calls. This reduces redundant data fetching and improves application performance.
3. **New Disarm Route**:
- As part of this refactor, a new disarm route is introduced that better aligns with our current architecture and security model.
> feat: remove unnecessary Zeroizing logic & add `cached` macro

- crates/nebula-authorization/src/server/router/mod.rs
This pull request introduces a feature that standardizes field names in JSON responses to camelCase format.
> feat: apply camelCase to JSON field names in response

- crates/nebula-authorization/src/application.rs
- crates/nebula-authorization/src/config.rs
- crates/nebula-authorization/src/domain/connector/saml.rs
Make SAML configuration fields optional for increased flexibility.
This pull request introduces a change in the SAML configuration by making certain fields optional.
> feat: make SAML config fields optional for flexibility

- crates/nebula-storage/src/backend/postgres.rs
This pull request refactors PostgreSQL queries in our codebase by removing redundant semicolons
> refactor(postgres): remove redundant semicolons from queries

- .dockerignore
- crates/nebula-authority/Dockerfile
- crates/nebula-authorization/Dockerfile
This pull request introduces Dockerfiles for nebula projects.
> feat: add Dockerfiles for nebula projects

- crates/nebula-authority/src/config.rs
- crates/nebula-authority/src/server/mod.rs
- crates/nebula-authorization/src/application.rs
- crates/nebula-authorization/src/config.rs
- crates/nebula-authorization/src/domain/connector/saml.rs
- crates/nebula-authorization/src/server/mod.rs
This pull request refactors the router in our codebase. The changes introduce the using path prefix. Additionally, to enhance data consistency and integrity, an `entity_id` is now required for operations .
> refactor(router): simplify path structure & require entity_id

- crates/nebula-backbone/src/application/parameter/mod.rs
- crates/nebula-backbone/src/server/router/parameter/mod.rs
- crates/nebula-backbone/src/server/router/parameter/response/mod.rs
This feature introduces the functionality to create a global parameters. It allows users to add new parameters through the application interface as needed.
> feat(backbone): add create global parameter functionality

- docs/docusaurus.config.ts
This pull request addresses an issue with link handling in our documentation.
> docs: fix link handling

- crates/nebula-backbone/src/application/authority/mod.rs
- crates/nebula-backbone/src/application/mod.rs
- crates/nebula-backbone/src/database/authority.rs
- crates/nebula-backbone/src/database/mod.rs
- crates/nebula-backbone/src/database/workspace_migration/m20241128_001_create_authority_table.rs
- crates/nebula-backbone/src/database/workspace_migration/mod.rs
- crates/nebula-backbone/src/domain/authority/mod.rs
- crates/nebula-backbone/src/domain/mod.rs
- crates/nebula-backbone/src/server/mod.rs
- crates/nebula-backbone/src/server/router/authority/mod.rs
- crates/nebula-backbone/src/server/router/authority/request.rs
- crates/nebula-backbone/src/server/router/authority/response.rs
- crates/nebula-backbone/src/server/router/mod.rs
This PR implements an API for registering authority servers. Access control is not implemented at this stage and should be added later when the access control logic is developed.
> impl registering authority feature

- crates/nebula-backbone/src/application/authority/mod.rs
- crates/nebula-backbone/src/domain/authority/mod.rs
- crates/nebula-backbone/src/server/router/authority/mod.rs
- crates/nebula-backbone/src/server/router/authority/response.rs
- crates/nebula-miracl/src/x509.rs
- crates/nebula-policy/src/utils.rs
- crates/nebula-token/src/jwt.rs
This PR implements an API for retrieving registered authority servers.
> impl getting authority feature

- crates/nebula-backbone/src/application/authority/mod.rs
- crates/nebula-backbone/src/domain/authority/mod.rs
- crates/nebula-backbone/src/server/router/authority/mod.rs
- crates/nebula-backbone/src/server/router/authority/request.rs
This PR implements an API for editing and deleting registered authority servers.
> impl managing authority api

- crates/nebula-backbone/src/domain/secret/mod.rs
The main update in this PR involves refining the path filtering functionality to utilize exact matching. This refactor makes our system more accurate by ensuring that only the precisely intended paths are captured and acted upon. Previously, our filtering might have included unintended matches due to a broader interpretation of path criteria. This enhancement will prevent such issues and improve overall reliability.
> refactor: update path filter to exact match

- Cargo.lock
- Cargo.toml
- crates/nebula-authority/Cargo.toml
- crates/nebula-authority/src/config.rs
- crates/nebula-authority/src/server/mod.rs
- crates/nebula-authorization/Cargo.toml
- crates/nebula-authorization/src/config.rs
- crates/nebula-authorization/src/server/mod.rs
- crates/nebula-backbone/Cargo.toml
- crates/nebula-backbone/src/config.rs
- crates/nebula-backbone/src/server/mod.rs
Summary of the changes: Integrates CORS support with customizable configuration options to enhance the security and flexibility of our API interactions.
This PR introduces support for Cross-Origin Resource Sharing (CORS) to our application, allowing API responses to be shared across different origins based on specified configuration options.
> feat(cors): integrate CORS support with config options

- crates/nebula-backbone/src/server/mod.rs
- crates/nebula-backbone/src/server/router/parameter/mod.rs
- crates/nebula-backbone/src/server/router/workspace/mod.rs
This pull request implements a structural refactor of the application's routing logic by separating public routes, which do not require JWT verification, from protected routes that do enforce such security measures.
> refactor(backbone): separate public and protected routes

- crates/nebula-abe/src/lib.rs
This pull request introduces a new feature in the ABE module by exposing the `PolicyLanguage` enum for external use. This enhancement allows developers to utilize the `PolicyLanguage` when setting values for encryption, providing more flexibility and control over policy configuration.
> feat(abe): expose PolicyLanguage for external use

- crates/nebula-authority/src/config.rs
- crates/nebula-authority/src/domain/authority.rs
- crates/nebula-authority/src/domain/backbone.rs
This pull request refactors the host handling by converting it to use the Url type. The primary goal of this change is to enhance the flexibility and reliability of URL manipulation within our codebase.
> refactor: use Url type for host to improve URL handling

- Cargo.lock
- Cargo.toml
- crates/nebula-backbone/Cargo.toml
- crates/nebula-backbone/src/application/path/mod.rs
- crates/nebula-backbone/src/application/secret/mod.rs
- crates/nebula-backbone/src/domain/secret/mod.rs
- crates/nebula-backbone/src/domain/secret/path_policy/mod.rs
- crates/nebula-backbone/src/domain/secret/path_policy/pest/mod.rs
- crates/nebula-backbone/src/domain/secret/path_policy/pest/policy.pest
- crates/nebula-backbone/src/server/mod.rs
- crates/nebula-backbone/src/server/router/path/mod.rs
- crates/nebula-backbone/src/server/router/path/response.rs
- crates/nebula-backbone/src/server/router/secret/mod.rs
- crates/nebula-backbone/src/server/router/secret/response/mod.rs
- crates/nebula-backbone/src/server/router/workspace/mod.rs
- crates/nebula-policy/Cargo.toml
This PR controls access to paths and secrets based on the policy provided for the path.
> Control secret and path access

- .github/workflows/build-docker.yaml
- .github/workflows/ci-nebula.yaml
This pull request consolidates and refines the CI and Docker build processes for the Nebula project.
> feat(ci): add to the build docker

- .github/workflows/build-docker.yaml
> fix: enable CI and set version from tags in workflow

- crates/nebula-authority/src/config.rs
- crates/nebula-authority/src/domain/authority.rs
- crates/nebula-authority/src/server/mod.rs
- crates/nebula-authorization/src/application.rs
- crates/nebula-authorization/src/config.rs
- crates/nebula-authorization/src/domain/connector/saml.rs
This pull request includes refactoring of the SAML attributes to improve their structure and usage within the application. It also involves modifications to the BackboneConfig to enhance approachability for configuration management
> refactor: update SAML attributes & modify BackboneConfig

- crates/nebula-authority/src/main.rs
- crates/nebula-backbone/src/application/mod.rs
- crates/nebula-token/src/auth/jwks_discovery.rs
This pull request focuses on refactoring the JWKS handling mechanisms within our system. The update includes optimizations in the initialization phase and better error management strategies to mitigate potential issues during the JWKS retrieval and processing. These changes aim to enhance the reliability and maintainability of the components dependent on JWKS.
> refactor: update jwks handling to improve initialization and error management

- .db.env.example
- .gitignore
- config/authority_config.toml.example
- config/authorization_config.toml.example
- config/backbone_config.toml.example
- docker-compose.yaml
This pull request introduces initial support for Docker compose to the project. It includes example Docker compose configuration files to help users containerize and run their application consistently across different environments.
> feat: add initial Docker support with example configs

- crates/nebula-backbone/src/application/path/mod.rs
- crates/nebula-backbone/src/application/secret/mod.rs
- crates/nebula-backbone/src/domain/secret/mod.rs
- crates/nebula-backbone/src/server/router/secret/mod.rs
This PR determines whether access to secrets is allowed based on the secret conditions.
> check secret access condition when accesssing secret

- crates/nebula-cli/src/api/authority.rs
- crates/nebula-cli/src/api/backbone.rs
- crates/nebula-cli/src/command/access_condition.rs
- crates/nebula-cli/src/command/authority.rs
- crates/nebula-cli/src/command/mod.rs
- crates/nebula-cli/src/command/path.rs
- crates/nebula-cli/src/command/secret.rs
This pull request introduces several new CLI functionalities aimed at enhancing the authority and path management capabilities. 
1. **Authority Commands:**
0fb941be89c26c0f2f9186570fdb5f8826157bbb f7924b183ffede1460a237316f34becc62becc49
- `list`: This command allows users to view the list of authorities registered within the backbone.
- `add`: Enables the addition of new authorities to the backbone.
- `init`: Distributes the master key of the authority server using secret sharing.
- `disarm`: Recovers the master key from the secret sharing results obtained during `init`.
2. **Path Commands:**
74df10a83169f270311ed9965cec7b97fe260501 f7924b183ffede1460a237316f34becc62becc49
- `create`: Permits the creation of new paths. 
- *Note that the policy …
> feat(cli): add new CLI functionalities for authority, path, and policy

- Cargo.lock
- Cargo.toml
- config/backbone_config.toml.example
- crates/nebula-authorization/Cargo.toml
- crates/nebula-authorization/src/database/mod.rs
- crates/nebula-authorization/src/domain/workspace/mod.rs
- crates/nebula-authorization/src/server/router/mod.rs
- crates/nebula-backbone/Cargo.toml
- crates/nebula-backbone/src/application/authority/mod.rs
- crates/nebula-backbone/src/application/mod.rs
- crates/nebula-backbone/src/application/parameter/mod.rs
- crates/nebula-backbone/src/application/path/mod.rs
- crates/nebula-backbone/src/application/policy/mod.rs
- crates/nebula-backbone/src/application/secret/mod.rs
- crates/nebula-backbone/src/application/workspace/mod.rs
- crates/nebula-backbone/src/config.rs
- crates/nebula-backbone/src/database/mod.rs
- crates/nebula-backbone/src/domain/workspace/mod.rs
- crates/nebula-backbone/src/domain/workspace/workspace_service.rs
- crates/nebula-backbone/src/server/router/workspace/mod.rs
- crates/nebula-backbone/src/server/router/workspace/response/mod.rs
- crates/nebula-common/Cargo.toml
- crates/nebula-common/src/lib.rs
This pull request introduces key features to enhance the workspace management system, focusing on validation and configuration improvements. 
1. **Workspace Name Validation:**
822177e448cd54e8940177a49f701bf64db4ecba 8043bf70df386b73e587d683f6ba364759378616 2532de629adc93ad1d4550456c2a05a356921de4 764fbeda0e142922219473d93436b0ff05dac33b 9995f7d1123369826cee5e06c75283d1e27ef0fc
- Implemented restrictions for workspace names, allowing only ASCII alphanumeric characters and ensuring names are under 255 characters. This change helps maintain consistency and prevent invalid entries.
2. **Naming Conventions Update:**
1c4dd542f450d8675ec58eed4e15e36bb5755989
- Updated the transaction object naming from "Organization" to "Workspace" to align with new …
> feat: validate workspace name and make configurable workspace handling

- crates/nebula-authority/src/server/router/init/mod.rs
This pull request introduces validation logic for secret shares and the threshold in the authority module. The changes ensure that secret shares meet defined criteria and that the threshold values are within acceptable ranges for the functionality of the module.
> feat(authority): add validation for secret shares and threshold

- crates/nebula-storage/src/shield/aes.rs
This pull request simplifies the logic used for shield key assignment.
> chore: simplify shield key assignment logic

- docker-compose.build.yaml
This pull request focuses on refactoring the Docker setup to improve the process of building images locally.
Run local build:
```sh
$ docker-compose -f docker-compose.build.yaml up -d 
```
> build: refactor Docker setup for local image building

- crates/nebula-authorization/src/application.rs
This pull request addresses an issue in the authentication module where the JSON Web Key (JWK) URL, identified by the `jku` parameter, previously failed to correctly incorporate the path prefix.
> fix(auth): update token service URL construction

- crates/nebula-authorization/src/domain/connector/saml.rs
This pull request addresses a bug in the SAMLConnector where a missing claim attribute could lead to unexpected errors. The update ensures that such scenarios are handled gracefully.
> fix: handle missing claim attribute in SAMLConnector

- .github/workflows/cli-build.yaml
- .github/workflows/cli-release.yaml
- scripts/cli_install.sh
This pull request focuses on improving the CI workflows and release strategies for our CLI tool.
> feat(ci): add GitHub Actions workflow for multi-platform CLI builds

- Cargo.lock
- Cargo.toml
- crates/nebula-backbone/src/application/workspace/mod.rs
this PR fix to use workspace schema as search path when creating workspace. because there is logic that inserting path and parameter in initializing sequence.
> use creating workspace schema when creating workspace

- crates/nebula-backbone/src/application/workspace/mod.rs
this PR fixes borkne test that tests workspace initialization
> fix creating workspace test

- Cargo.lock
- Cargo.toml
- crates/nebula-authorization/src/domain/machine_identity/mod.rs
- crates/nebula-authorization/src/server/router/mod.rs
this pr implements feature that adding location header to POST machine identity response. this is required for client operations such as creating machine identities and immediately assigning attributes to the generated identities.
> add location header to post machine identity response

- Cargo.lock
- Cargo.toml
- crates/nebula-backbone/src/domain/secret/mod.rs
This PR fixes the behavior of attempting to insert an empty array into PostgreSQL when trying to clear the Applied Policy of a Path.
> Fix inserting empty applied path policies

- config/authorization_config.toml.example
- config/backbone_config.toml.example
This PR removes workspace-specific configurations from example files.
> chore: remove workspace configs from example files
